@startuml

PROJECT_USER --> PROJECT
PROJECT_USER --> USER
TICKET --> USER
TICKET --> PROJECT
EVENT --> TICKET

class USER {
    PK id
    username
    email
    password
    profile_pict
}

class PROJECT {
    PK id
    name
}

class PROJECT_USER {
    PK id
    FK user_id
    FK project_id
}


class TICKET{
    PK id
    name
    description
    status
    total_time
    marked
    FK user_id
    FK project_id
}

class EVENT {
    PK id
    name
    date
    FK ticket_id
}


@enduml